# Continuous Integration (CI) Workflow
name: ci

# Triggers the workflow on pull request or push events for the specified branches
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Defines the jobs to run
jobs:
  # Linting job
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install node dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  # Dockerfile linting job
  dockerfile-lint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  # Docker Hub build and push job
  docker-hub:
    name: Build and Push to Docker Hub
    needs: [lint, dockerfile-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        env:
          DOCKERHUB_REPO: fushion23/fragments
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.SHA_TAG }}, ${{ env.DOCKERHUB_REPO }}:main, ${{ env.DOCKERHUB_REPO }}:latest
